from bpy.props import BoolProperty, EnumProperty

from math import pi

from .cloud_fk_chain import CloudFKChainRig

class CloudShoulderRig(CloudFKChainRig):
	"""A single bone control to connect an arm to a spine."""

	def initialize(self):
		super().initialize()
		"""Gather and validate data about the rig."""
		if len(self.bones.org.main)>1:
			print(f"""Shoulder rig on {self.base_bone} has a chain of more than a single bone. 
				   The rig only requires one bone, the rest will be unaffected!""")

	def prepare_bones(self):
		super().prepare_bones()
		self.prepare_fk_shoulder()

	def prepare_fk_shoulder(self):
		control = self.fk_chain[0]
		control.custom_shape = self.load_widget("Clavicle")
		self.register_parent(control, self.side_prefix.capitalize() + " Shoulder")
		shoulder_rot = int(self.params.CR_shoulder_up_axis)
		if shoulder_rot != 0:
			dsp_bone = self.create_dsp_bone(control, center=False)
			dsp_bone.roll += pi/2*shoulder_rot

		parent = self.get_bone(self.base_bone).parent
		if parent:
			control.parent = parent.name

	##############################
	# Parameters

	@classmethod
	def add_parameters(cls, params):
		""" Add the parameters of this rig type to the
			RigifyParameters PropertyGroup
		"""
		super().add_parameters(params)

		params.CR_shoulder_show_settings = BoolProperty(name="Shoulder Settings")
		params.CR_shoulder_up_axis = EnumProperty(
			name = "Up Axis"
			,description = "Rotate the bone shape to align with this axis of the bone"
			,items = [
				("0", '+Z', "Do not rotate the bone shape", 0),
				("1", '+X', "Rotate bone shape by 90 degrees", 1),
				("2", '-Z', "Rotate bone shape by 180 degrees", 2),
				("3", '-X', "Rotate bone shape by -90 degrees", 3),
			]
		)

	@classmethod
	def cloud_params_ui(cls, layout, params):
		""" Create the ui for the rig parameters.
		"""
		layout = super().cloud_params_ui(layout, params)

		if not cls.cloud_dropdown_ui(layout, params, "CR_shoulder_show_settings"): return layout

		layout.prop(params, 'CR_shoulder_up_axis')

		return layout

class Rig(CloudShoulderRig):
	pass

import bpy
def create_sample(obj):
	# generated by rigify.utils.write_metarig
	bpy.ops.object.mode_set(mode='EDIT')
	arm = obj.data

	bones = {}

	bone = arm.edit_bones.new('Shoulder.L')
	bone.head = 0.0231, -0.0234, 1.2487
	bone.tail = 0.1131, 0.0042, 1.2508
	bone.roll = -0.0235
	bone.use_connect = False
	bone.bbone_x = 0.0113
	bone.bbone_z = 0.0113
	bone.head_radius = 0.0111
	bone.tail_radius = 0.0133
	bone.envelope_distance = 0.0778
	bone.envelope_weight = 1.0000
	bone.use_envelope_multiply = 0.0000
	bones['Shoulder.L'] = bone.name
	bone = arm.edit_bones.new('UpperArm.L')
	bone.head = 0.1131, 0.0042, 1.2508
	bone.tail = 0.3176, 0.0138, 1.2407
	bone.roll = -1.5214
	bone.use_connect = True
	bone.bbone_x = 0.0121
	bone.bbone_z = 0.0121
	bone.head_radius = 0.0133
	bone.tail_radius = 0.0112
	bone.envelope_distance = 0.0448
	bone.envelope_weight = 1.0000
	bone.use_envelope_multiply = 0.0000
	bone.parent = arm.edit_bones[bones['Shoulder.L']]
	bones['UpperArm.L'] = bone.name
	bone = arm.edit_bones.new('Forearm.L')
	bone.head = 0.3176, 0.0138, 1.2407
	bone.tail = 0.5288, -0.0125, 1.2312
	bone.roll = -1.5260
	bone.use_connect = True
	bone.bbone_x = 0.0107
	bone.bbone_z = 0.0107
	bone.head_radius = 0.0112
	bone.tail_radius = 0.0132
	bone.envelope_distance = 0.0526
	bone.envelope_weight = 1.0000
	bone.use_envelope_multiply = 0.0000
	bone.parent = arm.edit_bones[bones['UpperArm.L']]
	bones['Forearm.L'] = bone.name
	bone = arm.edit_bones.new('Wrist.L')
	bone.head = 0.5288, -0.0125, 1.2312
	bone.tail = 0.5842, -0.0197, 1.2286
	bone.roll = -1.5240
	bone.use_connect = True
	bone.bbone_x = 0.0139
	bone.bbone_z = 0.0139
	bone.head_radius = 0.0132
	bone.tail_radius = 0.0056
	bone.envelope_distance = 0.0222
	bone.envelope_weight = 1.0000
	bone.use_envelope_multiply = 0.0000
	bone.parent = arm.edit_bones[bones['Forearm.L']]
	bones['Wrist.L'] = bone.name

	bpy.ops.object.mode_set(mode='OBJECT')
	pbone = obj.pose.bones[bones['Shoulder.L']]
	pbone.rigify_type = 'cloud_shoulder'
	pbone.lock_location = (False, False, False)
	pbone.lock_rotation = (False, False, False)
	pbone.lock_rotation_w = False
	pbone.lock_scale = (False, False, False)
	pbone.rotation_mode = 'QUATERNION'

	try:
		pbone.rigify_parameters.CR_deform_segments = 1
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_sharp_sections = True
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_cap_control = False
	except AttributeError:
		pass
	pbone = obj.pose.bones[bones['UpperArm.L']]
	pbone.rigify_type = 'cloud_limbs'
	pbone.lock_location = (False, False, False)
	pbone.lock_rotation = (False, False, False)
	pbone.lock_rotation_w = False
	pbone.lock_scale = (False, False, False)
	pbone.rotation_mode = 'QUATERNION'
	try:
		pbone.rigify_parameters.CR_world_aligned_controls = False
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_double_first_control = False
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_double_ik_control = False
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_use_custom_category_name = False
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_use_custom_limb_name = False
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_cap_control = False
	except AttributeError:
		pass
	try:
		pbone.rigify_parameters.CR_center_all_fk = True
	except AttributeError:
		pass

	pbone = obj.pose.bones[bones['Forearm.L']]
	pbone.rigify_type = ''
	pbone.lock_location = (False, False, False)
	pbone.lock_rotation = (False, False, False)
	pbone.lock_rotation_w = False
	pbone.lock_scale = (False, False, False)
	pbone.rotation_mode = 'QUATERNION'
	pbone = obj.pose.bones[bones['Wrist.L']]
	pbone.rigify_type = ''
	pbone.lock_location = (False, False, False)
	pbone.lock_rotation = (False, False, False)
	pbone.lock_rotation_w = False
	pbone.lock_scale = (False, False, False)
	pbone.rotation_mode = 'QUATERNION'

	bpy.ops.object.mode_set(mode='EDIT')
	for bone in arm.edit_bones:
		bone.select = False
		bone.select_head = False
		bone.select_tail = False
	for b in bones:
		bone = arm.edit_bones[bones[b]]
		bone.select = True
		bone.select_head = True
		bone.select_tail = True
		arm.edit_bones.active = bone

	return bones