# Operators to move some data from the generated rig back to the metarig.
# This could be bones, constraints, drivers, custom properties,
# but the UX for some of those is maybe not worth solving.
# Bones and constraints would be great though.

import bpy
from bpy.props import EnumProperty
from bpy.types import Context, Operator

from ..bs_utils.properties import copy_property_group
from ..generation.cloudrig import find_metarig_of_rig, is_active_cloudrig, object_mode
from ..utils.rig import get_selected_bone_tuples
from .render_thumbnail import temporary_setattr


class OBJECT_OT_cloudrig_push_to_metarig(Operator):
    """Push a bone from a generated rig over to the metarig."""

    bl_idname = "object.cloudrig_push_to_metarig"
    bl_label = "Push Bone to Metarig"
    bl_options = {'REGISTER', 'UNDO'}

    push_component_type: EnumProperty(
        name="Component Type",
        items=[
            ('COPY', "Copy", "Control will be copied to the generated rig."),
            ('TWEAK', "Tweak", "Bone generated by another component will be tweaked."),
        ],
    )

    @classmethod
    def poll(cls, context):
        rig = is_active_cloudrig(context)
        return all((
            rig,
            bpy.ops.pose.separate_selected_bones.poll(),
            context.mode in ('EDIT_ARMATURE', 'POSE'),
            find_metarig_of_rig(context, rig),
        ))

    def invoke(self, context: Context, _event):
        return context.window_manager.invoke_props_dialog(self, width=400)

    def draw(self, context: Context):
        sel_bones = get_selected_bone_tuples(context)
        self.layout.label(text="Push {num_bones} bones to metarig as:".format(num_bones=len(sel_bones)))
        self.layout.prop(self, 'push_component_type', expand=True)

    def execute(self, context: Context):
        generated_rig = context.active_object

        org_mode = generated_rig.mode

        # Switch to metarig just to make sure we are able to.
        res = bpy.ops.object.cloudrig_metarig_toggle(match_selection=False)
        if res == {'CANCELLED'}:
            self.report({'ERROR'}, "Failed to make metarig visible.")

        # Switch back.
        bpy.ops.object.cloudrig_metarig_toggle(match_selection=False)

        # Duplicate the selected bones (Without symmetry)
        # This removes their drivers, keeps their constraints,
        # and puts .00x at the end of their names.
        for bone in generated_rig.data.bones:
            bone.hide = False
        with temporary_setattr(
                generated_rig.data,
                use_mirror_x=False,
            ), object_mode(
                generated_rig,
                mode='EDIT',
            ):
            # Store the original bone names...
            for ebone in generated_rig.data.edit_bones:
                if ebone.select:
                    ebone['name'] = ebone.name
            bpy.ops.armature.duplicate()
            # Mangle the new bone names...
            for ebone in generated_rig.data.edit_bones:
                if ebone.select:
                    ebone.name += "___"

        # Separate selected bones into a new armature object.
        bpy.ops.pose.separate_selected_bones()
        separated_arm_obj = context.active_object

        # Nuke all drivers in the separated armature.
        separated_arm_obj.animation_data_clear()

        # Switch back to metarig.
        context.view_layer.objects.active = generated_rig
        bpy.ops.object.cloudrig_metarig_toggle(match_selection=False)
        metarig = context.view_layer.objects.active

        # Merge that armature object into the metarig.
        separated_arm_obj.select_set(True)
        # Store bone names...
        separated_bone_names = [pb.name for pb in separated_arm_obj.pose.bones]
        assert not any((bone_name in metarig.pose.bones for bone_name in separated_bone_names))
        bpy.ops.object.join()
        separated_arm_obj = None

        # Replace the bones if they exist.
        comp_names = {
            'COPY': "Raw Copy",
            'TWEAK': "Bone Tweak",
        }
        bpy.ops.object.mode_set(mode='EDIT')
        metarig = context.active_object
        for bone_name in separated_bone_names:
            new_ebone = metarig.data.edit_bones.get(bone_name)
            new_pbone = metarig.pose.bones.get(bone_name)
            assert new_ebone and new_pbone
            old_pb = metarig.pose.bones.get(new_ebone['name'])
            if old_pb:
                # Preserve the cloudrig component.
                copy_property_group(old_pb.cloudrig_component, new_pbone.cloudrig_component, x_mirror=False)

            new_pbone.cloudrig_component.component_type = comp_names[self.push_component_type]

            old_eb = metarig.data.edit_bones.get(new_ebone['name'])
            if old_eb:
                metarig.data.edit_bones.remove(old_eb)

            new_ebone.name = new_ebone['name']
            del new_ebone['name']
        bpy.ops.object.mode_set(mode=org_mode)

        return {'FINISHED'}

registry = [
    OBJECT_OT_cloudrig_push_to_metarig,
]
