# SPDX-License-Identifier: GPL-3.0-or-later

import bpy
from bpy.app.translations import pgettext_iface as iface_
from bpy.props import EnumProperty
from bpy.types import Context, Event, Operator

from ..bs_utils.properties import copy_property_group
from ..generation.cloudrig import find_metarig_of_rig, is_active_cloudrig, object_mode
from ..rig_component_features.mechanism import copy_driver
from ..utils.rig import get_selected_bone_tuples
from .render_thumbnail import temporary_setattr
from .toggle_metarig import metarig_context_switch


class OBJECT_OT_cloudrig_push_to_metarig(Operator):
    """Push a bone from a generated rig over to the metarig."""

    bl_idname = "object.cloudrig_push_to_metarig"
    bl_label = "Push Bone to Metarig"
    bl_options = {'REGISTER', 'UNDO'}

    push_component_type: EnumProperty(
        name="Component Type",
        items=[
            ('COPY', "Copy", "Control will be copied to the generated rig."),
            ('TWEAK', "Tweak", "Bone generated by another component will be tweaked."),
        ],
    )

    @classmethod
    def poll(cls, context: Context):
        rig = is_active_cloudrig(context)
        if not rig:
            cls.poll_message_set("No active armature.")
            return False
        if context.mode not in ('EDIT_ARMATURE', 'POSE'):
            cls.poll_message_set("Must be in Pose/Edit mode.")
            return False
        if not find_metarig_of_rig(context, rig):
            cls.poll_message_set("MetaRig not found!")
            return False
        if not bpy.ops.pose.separate_selected_bones.poll():
            cls.poll_message_set("Must have selected pose/edit bones.")
            return False
        return True

    def invoke(self, context: Context, _event: Event):
        return context.window_manager.invoke_props_dialog(self, width=400)

    def draw(self, context: Context):
        sel_bones = get_selected_bone_tuples(context)
        self.layout.label(text=iface_("Push {num_bones} bones to metarig as:").format(num_bones=len(sel_bones)))
        self.layout.prop(self, 'push_component_type', expand=True)

    def execute(self, context: Context):
        # TODO: This function could be significantly less nightmarish if it used BoneInfo read/write, although that could also get complicated...
        generated_rig = context.active_object

        org_mode = generated_rig.mode

        # Switch to metarig just to make sure we are able to.
        # This may error and interrupt this operator, which is fine.
        ret = metarig_context_switch(context, match_selection=False)
        if ret:
            self.report({'ERROR'}, ret)
            return {'CANCELLED'}

        # Snatch a reference, then switch back.
        metarig = context.view_layer.objects.active
        metarig_context_switch(context, match_selection=False)

        # Duplicate the selected bones (Without symmetry)
        # This removes their drivers, keeps their constraints,
        # and puts .00x at the end of their names.
        bone_names = {}
        for bone in generated_rig.data.bones:
            bone.hide = False
        with (
            temporary_setattr(
                generated_rig.data,
                use_mirror_x=False,
            ),
            object_mode(
                generated_rig,
                mode='EDIT',
            ),
        ):
            # Store the original bone names and parents.
            for ebone in generated_rig.data.edit_bones:
                if ebone.select:
                    ebone['name'] = ebone.name
                    if ebone.parent:
                        bone_names[ebone.name] = ebone.parent.name
                    else:
                        bone_names[ebone.name] = ""
            bpy.ops.armature.duplicate()
            # Mangle the new bone names to be extra sure of avoiding conflicts when joining the two armatures.
            for ebone in generated_rig.data.edit_bones:
                if ebone.select:
                    ebone.name += "___"

        # Separate selected bones into a new armature object.
        bpy.ops.pose.separate_selected_bones()
        separated_arm_obj = context.active_object

        # Nuke drivers.
        separated_arm_obj.animation_data_clear()
        separated_arm_obj.data.animation_data_clear()

        # Switch back to metarig.
        context.view_layer.objects.active = generated_rig
        metarig_context_switch(context, match_selection=False)
        metarig = context.view_layer.objects.active

        # Merge that armature object into the metarig.
        separated_arm_obj.select_set(True)
        # Store bone names...
        separated_bone_names = [pb.name for pb in separated_arm_obj.pose.bones]
        assert not any(bone_name in metarig.pose.bones for bone_name in separated_bone_names)
        bpy.ops.object.join()
        separated_arm_obj = None

        # Replace the bones if they exist.
        comp_names = {
            'COPY': "Raw Copy",
            'TWEAK': "Bone Tweak",
        }
        bpy.ops.object.mode_set(mode='EDIT')
        metarig = context.active_object
        for bone_name in separated_bone_names:
            new_ebone = metarig.data.edit_bones.get(bone_name)
            new_pbone = metarig.pose.bones.get(bone_name)
            assert new_ebone and new_pbone
            old_pb = metarig.pose.bones.get(new_ebone['name'])
            if old_pb:
                # Preserve the cloudrig component.
                copy_property_group(old_pb.cloudrig_component, new_pbone.cloudrig_component, x_mirror=False)

            new_pbone.cloudrig_component.component_type = comp_names[self.push_component_type]

            old_eb = metarig.data.edit_bones.get(new_ebone['name'])
            if old_eb:
                metarig.data.edit_bones.remove(old_eb)

            new_ebone.name = new_ebone['name']
            del new_ebone['name']
        bpy.ops.object.mode_set(mode=org_mode)

        # Achieve parenting with an Armature constraint.
        for bone_name, parent_name in bone_names.items():
            if not parent_name:
                continue
            pbone = metarig.pose.bones.get(bone_name)
            if not pbone:
                continue
            arm_con = pbone.constraints.new(type='ARMATURE')
            pbone.constraints.move(len(pbone.constraints) - 1, 0)
            arm_con.name = "NOHLP_Armature@" + parent_name
            arm_con.targets.new()

        # Copy drivers.
        ids = [(generated_rig, metarig), (generated_rig.data, metarig.data)]
        for src_id, tgt_id in ids:
            if not src_id.animation_data:
                continue
            for fcurve in src_id.animation_data.drivers:
                if any(f'bones["{bone}"]' in fcurve.data_path for bone in bone_names):
                    copy_driver(fcurve, tgt_id)

        return {'FINISHED'}


registry = [
    OBJECT_OT_cloudrig_push_to_metarig,
]
