from . import (
    # assign_bone_layers,
    better_bone_extrude,
    bone_selection_pie_ops,
    bone_selection_pie_ui,
    edit_widget,
    flatten_chain,
    pie_bone_parenting,
    pie_bone_specials,
    symmetrize,
    toggle_action_constraints,
    toggle_metarig,
    copy_mirror_components,
    bone_collections_popup,
)

modules = [
    # assign_bone_layers,
    better_bone_extrude,
    bone_selection_pie_ops,
    bone_selection_pie_ui,
    edit_widget,
    flatten_chain,
    pie_bone_parenting,
    pie_bone_specials,
    symmetrize,
    toggle_action_constraints,
    toggle_metarig,
    copy_mirror_components,
    bone_collections_popup,
]
